#!/bin/bash
# ============================================================================
# WATERCODEFLOW EXTENSION - CLEANUP
# ============================================================================
# Deletes all build artifacts and node_modules so the repo is back to a
# clean source-only state. Run full_setup.sh again to rebuild from scratch.
#
# Removes:
#   - build/                      (C++ compiled output)
#   - editor/out/                 (compiled TypeScript)
#   - editor/node_modules/        (npm packages)
#   - editor/*.vsix               (packaged extensions)
#   - setup.log                   (setup log from last run)
#   - CMakeCache / CMakeFiles      (stray cmake artefacts in root)
#   - All __pycache__ / *.pyc     (Python bytecode)
#   - All *.egg-info              (Python dist metadata)
# ============================================================================

set -e

BOLD='\033[1m'
GREEN='\033[92m'
YELLOW='\033[93m'
CYAN='\033[96m'
RESET='\033[0m'

EXTENSION_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EDITOR_DIR="$EXTENSION_ROOT/editor"

print_header() {
    echo -e "\n${BOLD}${CYAN}┌─────────────────────────────────────────────────────────────┐${RESET}"
    echo -e "${BOLD}${CYAN}│  $1${RESET}"
    echo -e "${BOLD}${CYAN}└─────────────────────────────────────────────────────────────┘${RESET}\n"
}

gone()    { echo -e "  ${GREEN}✓${RESET}  $1"; }
skipped() { echo -e "  ${YELLOW}–${RESET}  $1  (not found)"; }

rm_dir() {
    local path="$1" label="$2"
    if [ -d "$path" ]; then
        rm -rf "$path"
        gone "$label"
    else
        skipped "$label"
    fi
}

rm_file() {
    local path="$1" label="$2"
    if [ -f "$path" ]; then
        rm -f "$path"
        gone "$label"
    else
        skipped "$label"
    fi
}

rm_glob() {
    local pattern="$1" label="$2"
    local count
    count=$(find $pattern 2>/dev/null | wc -l)
    if [ "$count" -gt 0 ]; then
        find $pattern -exec rm -rf {} + 2>/dev/null || true
        gone "$label  ($count items)"
    else
        skipped "$label"
    fi
}

# ── Confirm ───────────────────────────────────────────────────────────────────

print_header "WATERCODEFLOW — CLEANUP"

echo -e "  This will delete all build artefacts and node_modules."
echo -e "  Run ${YELLOW}./full_setup.sh${RESET} afterwards to rebuild.\n"
read -rp "  Continue? (y/N): " confirm
if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
    echo "  Cancelled."
    exit 0
fi

# ── C++ build ─────────────────────────────────────────────────────────────────

print_header "C++ BUILD ARTEFACTS"

rm_dir  "$EXTENSION_ROOT/build"           "build/"
rm_dir  "$EXTENSION_ROOT/CMakeFiles"      "CMakeFiles/  (stray)"
rm_file "$EXTENSION_ROOT/CMakeCache.txt"  "CMakeCache.txt  (stray)"
rm_file "$EXTENSION_ROOT/cmake_install.cmake" "cmake_install.cmake  (stray)"
rm_file "$EXTENSION_ROOT/Makefile"        "Makefile  (stray root)"

# Compiled .so copies in storage_utility/ (regenerated by build)
rm_file "$EXTENSION_ROOT/storage_utility/faststorage_c.so" \
        "storage_utility/faststorage_c.so"
rm_file "$EXTENSION_ROOT/watcher/storage_utility/faststorage_c.so" \
        "watcher/storage_utility/faststorage_c.so"

# ── VS Code extension ──────────────────────────────────────────────────────────

print_header "VS CODE EXTENSION ARTEFACTS"

rm_dir  "$EDITOR_DIR/out"          "editor/out/"
rm_dir  "$EDITOR_DIR/node_modules" "editor/node_modules/"

# Remove all .vsix files in editor/
if ls "$EDITOR_DIR"/*.vsix 1>/dev/null 2>&1; then
    VSIX_COUNT=$(ls "$EDITOR_DIR"/*.vsix 2>/dev/null | wc -l)
    rm -f "$EDITOR_DIR"/*.vsix
    gone "editor/*.vsix  ($VSIX_COUNT file(s))"
else
    skipped "editor/*.vsix"
fi

rm_file "$EXTENSION_ROOT/setup.log" "setup.log"

# ── Python bytecode ───────────────────────────────────────────────────────────

print_header "PYTHON BYTECODE"

PYCACHE=$(find "$EXTENSION_ROOT" -type d -name "__pycache__" 2>/dev/null | wc -l)
if [ "$PYCACHE" -gt 0 ]; then
    find "$EXTENSION_ROOT" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    gone "__pycache__/  ($PYCACHE directories)"
else
    skipped "__pycache__ directories"
fi

PYCS=$(find "$EXTENSION_ROOT" -type f -name "*.pyc" 2>/dev/null | wc -l)
if [ "$PYCS" -gt 0 ]; then
    find "$EXTENSION_ROOT" -type f -name "*.pyc" -delete 2>/dev/null || true
    gone "*.pyc  ($PYCS files)"
else
    skipped "*.pyc files"
fi

PYTEST_CACHE=$(find "$EXTENSION_ROOT" -type d -name ".pytest_cache" 2>/dev/null | wc -l)
if [ "$PYTEST_CACHE" -gt 0 ]; then
    find "$EXTENSION_ROOT" -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
    gone ".pytest_cache/  ($PYTEST_CACHE directories)"
else
    skipped ".pytest_cache directories"
fi

EGGINFO=$(find "$EXTENSION_ROOT" -type d -name "*.egg-info" 2>/dev/null | wc -l)
if [ "$EGGINFO" -gt 0 ]; then
    find "$EXTENSION_ROOT" -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
    gone "*.egg-info/  ($EGGINFO directories)"
else
    skipped "*.egg-info directories"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

print_header "CLEANUP COMPLETE"

echo -e "  ${GREEN}${BOLD}All artefacts removed.${RESET}\n"
echo -e "  Rebuild with:  ${YELLOW}./full_setup.sh${RESET}\n"
